<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Palier.Domain\Palier.Domain.csproj" />
    <ProjectReference Include="..\Palier.Application\Palier.Application.csproj" />
    <ProjectReference Include="..\Palier.Infrastructure\Palier.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
